title: Tariere A. Timitimi
author: Tariere A. Timitimi

remote_theme: daattali/beautiful-jekyll

avatar: /assets/img/profile.jpeg
round-avatar: true

navbar-links:
  About: "#about"
  Tech Stack: "#tech-stack"
  Projects: "#projects"
  Certifications: "#certifications"
  
social-network-links:
  github: Tarieret
  kaggle: tarieretimitimi
  linkedin: tariere-timitimi
  email: tarieretimitimi@gmail.com

site-css:
  - /Portfolio/assets/css/style.css
